# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: freefire
    volumes:
      - ./postgres:/var/lib/postgresql/data

